version: '3.8'

services:
  bir_bilene_danis_backend:

    build: .
    container_name: bir_bilene_danis

    ports:
      - "5000:5000"
    
    restart: always
   
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production

  bir_bilene_danis_frontend:
    image: nginx:stable-alpine
    container_name: bir_bilene_danis_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - bir_bilene_danis_backend
